/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Librarian } from "./Librarian";
import { LibrarianCountArgs } from "./LibrarianCountArgs";
import { LibrarianFindManyArgs } from "./LibrarianFindManyArgs";
import { LibrarianFindUniqueArgs } from "./LibrarianFindUniqueArgs";
import { CreateLibrarianArgs } from "./CreateLibrarianArgs";
import { UpdateLibrarianArgs } from "./UpdateLibrarianArgs";
import { DeleteLibrarianArgs } from "./DeleteLibrarianArgs";
import { Library } from "../../library/base/Library";
import { LibrarianService } from "../librarian.service";
@graphql.Resolver(() => Librarian)
export class LibrarianResolverBase {
  constructor(protected readonly service: LibrarianService) {}

  async _librariansMeta(
    @graphql.Args() args: LibrarianCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Librarian])
  async librarians(
    @graphql.Args() args: LibrarianFindManyArgs
  ): Promise<Librarian[]> {
    return this.service.librarians(args);
  }

  @graphql.Query(() => Librarian, { nullable: true })
  async librarian(
    @graphql.Args() args: LibrarianFindUniqueArgs
  ): Promise<Librarian | null> {
    const result = await this.service.librarian(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Librarian)
  async createLibrarian(
    @graphql.Args() args: CreateLibrarianArgs
  ): Promise<Librarian> {
    return await this.service.createLibrarian({
      ...args,
      data: {
        ...args.data,

        library: args.data.library
          ? {
              connect: args.data.library,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Librarian)
  async updateLibrarian(
    @graphql.Args() args: UpdateLibrarianArgs
  ): Promise<Librarian | null> {
    try {
      return await this.service.updateLibrarian({
        ...args,
        data: {
          ...args.data,

          library: args.data.library
            ? {
                connect: args.data.library,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Librarian)
  async deleteLibrarian(
    @graphql.Args() args: DeleteLibrarianArgs
  ): Promise<Librarian | null> {
    try {
      return await this.service.deleteLibrarian(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Library, {
    nullable: true,
    name: "library",
  })
  async getLibrary(
    @graphql.Parent() parent: Librarian
  ): Promise<Library | null> {
    const result = await this.service.getLibrary(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
